name: Compila Kernel

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Scarica il repository
      uses: actions/checkout@v4

    - name: Installa NASM e GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm build-essential gcc-multilib

    - name: Compila bootloader (BIN)
      run: nasm -f bin boot.asm -o boot.bin

    - name: Compila porte.asm (ELF)
      run: nasm -f elf32 porte.asm -o porte.o

    - name: Compila kernel.cpp (ELF)
      run: g++ -m32 -ffreestanding -fno-pie -c kernel.cpp -o kernel.o

    - name: Comp
